// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.DoubleDate = (function() {

    DoubleDate.prototype.$hiddenInput = null;

    DoubleDate.prototype.settings = {
      dateFormat: "mm/dd/yy",
      altFormat: "yy-mm-dd"
    };

    function DoubleDate(options) {
      this._onInputChange = __bind(this._onInputChange, this);

      this._formatDate = __bind(this._formatDate, this);

      var date;
      this.$el = $(options.el);
      this.options = $.extend({}, this.settings, options);
      this.$hiddenInput = this.$el.clone();
      this.$hiddenInput.attr("type", "hidden");
      date = new Date("" + (this.$el.val()) + " 00:00:00");
      if (this.$el.val()) {
        this.$hiddenInput.val(this._formatDate(this.options.altFormat, date));
        this.$el.val(this._formatDate(this.options.dateFormat, date));
      }
      this.$el.removeAttr("name").removeAttr("id");
      this.$el.after(this.$hiddenInput);
      this.$el.datepicker({
        dateFormat: this.options.dateFormat,
        altField: this.$hiddenInput,
        altFormat: this.options.altFormat
      });
      this.$el.bind("keyup", this._onInputChange);
    }

    DoubleDate.prototype._formatDate = function(format, date) {
      return $.datepicker.formatDate(format, date);
    };

    DoubleDate.prototype._onInputChange = function() {
      if (!this.$el.val()) {
        return this.$hiddenInput.val("");
      }
    };

    return DoubleDate;

  })();

}).call(this);
